apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
  labels:
    app: account
  namespace: itonk-11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: kasperhermansen/itonk11-account:1
          env:
            - name: RUNTIME_ENV
              value: TEST
            - name: POSTGRES_HOST
              value: account-db-service.itonk-11.svc.cluster.local
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_DB
              value: Accountdb
          ports:
            - containerPort: 80
          livenessProbe:
            initialDelaySeconds: 10
            failureThreshold: 10
            httpGet:
              path: /api/health/ping
              port: 80
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            initialDelaySeconds: 10
            failureThreshold: 10
            httpGet:
              path: /api/health/ping
              port: 80
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    app: account-service
  namespace: itonk-del1-11
spec:
  type: LoadBalancer
  selector:
    app: account
  ports:
    - name: http
      port: 80
      targetPort: 80
