// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PSO_Control_Service;

namespace PSO_Control_Service.Migrations
{
    [DbContext(typeof(PSO_Context))]
    [Migration("20190315205118_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("PSO_Control_Service.Models.ShareModel", b =>
                {
                    b.Property<int>("ShareId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ShareCount");

                    b.Property<string>("ShareName");

                    b.Property<int>("ShareValue");

                    b.Property<int?>("UserModelUserId");

                    b.HasKey("ShareId");

                    b.HasIndex("UserModelUserId");

                    b.ToTable("ShareModel");
                });

            modelBuilder.Entity("PSO_Control_Service.Models.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserPassword");

                    b.Property<string>("Username");

                    b.HasKey("UserId");

                    b.ToTable("UserModel");
                });

            modelBuilder.Entity("PSO_Control_Service.Models.ShareModel", b =>
                {
                    b.HasOne("PSO_Control_Service.Models.UserModel")
                        .WithMany("shares")
                        .HasForeignKey("UserModelUserId");
                });
#pragma warning restore 612, 618
        }
    }
}
