// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PSO_Control_Service;

namespace PSO_Control_Service.Migrations
{
    [DbContext(typeof(PSO_Context))]
    [Migration("20190318131446_fixed_models")]
    partial class fixed_models
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("PSO_Control_Service.Models.ShareModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Count");

                    b.Property<string>("Name");

                    b.Property<int?>("UserModelId");

                    b.Property<int>("Value");

                    b.HasKey("Id");

                    b.HasIndex("UserModelId");

                    b.ToTable("ShareModel");
                });

            modelBuilder.Entity("PSO_Control_Service.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("UserModel");
                });

            modelBuilder.Entity("PSO_Control_Service.Models.ShareModel", b =>
                {
                    b.HasOne("PSO_Control_Service.Models.UserModel")
                        .WithMany("Shares")
                        .HasForeignKey("UserModelId");
                });
#pragma warning restore 612, 618
        }
    }
}
