// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shares.Database;

namespace Shares.Migrations
{
    [DbContext(typeof(SharesContext))]
    internal class SharesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Shares.Models.Share", b =>
            {
                b.Property<Guid>("ShareId")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Name");

                b.Property<decimal>("SingleShareValue");

                b.Property<int>("TotalCount");

                b.Property<decimal>("TotalValue");

                b.HasKey("ShareId");

                b.ToTable("Shares");
            });
#pragma warning restore 612, 618
        }
    }
}