// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PublicShareControl;

namespace PublicShareControl.Migrations
{
    [DbContext(typeof(PSCContext))]
    [Migration("20190524213524_addedcomposite")]
    partial class addedcomposite
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("PublicShareControl.Models.Portfolio", b =>
                {
                    b.Property<Guid>("PortfolioId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("OwnerId");

                    b.HasKey("PortfolioId");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("PublicShareControl.Models.Share", b =>
                {
                    b.Property<Guid>("ShareId");

                    b.Property<Guid>("PortfolioId");

                    b.Property<int>("Count");

                    b.HasKey("ShareId", "PortfolioId");

                    b.HasIndex("PortfolioId");

                    b.ToTable("Share");
                });

            modelBuilder.Entity("PublicShareControl.Models.Share", b =>
                {
                    b.HasOne("PublicShareControl.Models.Portfolio", "Portfolio")
                        .WithMany("Shares")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
