apiVersion: apps/v1
kind: Deployment
metadata:
  name: pso-control-service
  labels:
    app: pso-control-service
  namespace: itonk-11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pso-control-service
  template:
    metadata:
      labels:
        app: pso-control-service
    spec:
      containers:
        - name: pso-control-service
          image: kasperhermansen/itonk11-pso-control-service:7
          env:
            - name: POSTGRES_HOST
              value: users-db-service.itonk-11.svc.cluster.local
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: usersdb
          ports:
            - containerPort: 80
          livenessProbe:
            initialDelaySeconds: 10
            failureThreshold: 10
            httpGet:
              path: /api/users
              port: 80
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            initialDelaySeconds: 10
            failureThreshold: 10
            httpGet:
              path: /api/users
              port: 80
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: pso-control-service
  labels:
    app: pso-control-service
  namespace: itonk-11
spec:
  type: LoadBalancer
  selector:
    app: pso-control-service
  ports:
    - name: http
      port: 80
      targetPort: 80
