FROM microsoft/dotnet:2.2-sdk-alpine AS build

WORKDIR /usr/src/app

COPY *.csproj ./
RUN dotnet restore

COPY ./ ./
RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:2.2-runtime-alpine AS runtime
WORKDIR /usr/src/app
COPY --from=build /usr/src/app/out ./
ENTRYPOINT ["dotnet", "--version"]