apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
  namespace: itonk-11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: kasperhermansen/itonk11-payment:4
          env:
            - name: RUNTIME_ENV
              value: PRODUCTION
            - name: POSTGRES_HOST
              value: db-service.itonk-11.svc.cluster.local
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_DB
              value: Paymentdb
            - name: USERS_SERVICE_DNS
              value: users-service.itonk-11.svc.cluster.local
            - name: USERS_SERVICE_PORT
              value: '80'
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: '128Mi'
              cpu: '100m'
          livenessProbe:
            initialDelaySeconds: 10
            failureThreshold: 10
            httpGet:
              path: /api/health/ping
              port: 80
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            initialDelaySeconds: 10
            failureThreshold: 10
            httpGet:
              path: /api/health/ping
              port: 80
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-service
  namespace: itonk-11
spec:
  type: LoadBalancer
  selector:
    app: payment
  ports:
    - name: http
      port: 80
      targetPort: 80
